spring:
  datasource:
    # 1. Mudamos de 'mem' para 'file' e definimos um caminho (ex: ./data/meubanco)
    url: jdbc:h2:file:./data/meubanco
    driver-class-name: org.h2.Driver
    username: raul
    password:

  h2:
    console:
      enabled: true
      # 2. Caminho do console (opcional, padrão é /h2-console)
      path: /h2-console

  jpa:
    hibernate:
      # 3. Garante que ele não apague as tabelas ao iniciar
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect